package com.crystalgui.headless;

import static org.junit.Assert.assertTrue;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import org.junit.Test;

/**
 * <b>"How far are we" is a query, not a feeling</b> — {@code tools/port/port-ledger.tsv} against the
 * tree it describes.
 *
 * <p>{@code plan_m6.md} §2.5. The ledger says, for each of the ported classes, where it goes, which
 * batch takes it, whether the codemod COPIES it or the IDE MOVES it, and whether it has moved yet;
 * and for each {@code __part__} name in every sheet, whether it is a shadow part (A), light-tree
 * structure (B) or a state flag (C). It is generated by {@code tools/port/ledger.py} from the tree
 * and the sheets, so it cannot drift into describing files that no longer exist — this asserts the
 * other direction: that nothing in scope is missing from it.</p>
 *
 * <h3>What this catches that a plan cannot</h3>
 *
 * <p>A plan is prose and goes stale silently; {@code AGENTS.md}'s own doc-count paragraph was wrong
 * three times running for exactly that reason. A ledger with a test under it fails on the commit
 * that adds a widget without saying where it goes, which is the moment the answer is cheapest.</p>
 */
public class PortLedgerTest {

    private static final String LEDGER = "tools/port/port-ledger.tsv";

    /** One row of the CLASS table. */
    private record ClassRow(String path, String destination, String batch, String how, String status) {
    }

    /**
     * One row of the PART table, keyed by (OWNER, name).
     *
     * <p>Not by name alone, and the first widget ported proved why: {@code __pre-icon__} is declared
     * by four classes and its kind differs between them — Button's own icon slot is a part (A), while
     * a window preview's holds a whole {@code WindowIcon} and has a rule reaching through it to the
     * monogram (B). {@code __label__}, {@code __content__}, {@code __icon__} and {@code __title__}
     * are shared the same way, and {@code .__content__} claimed by three unrelated widgets is a
     * standing invariant row — a table keyed by name reproduces exactly that mistake.</p>
     */
    private record PartRow(String owner, String name, String kind, String source) {
    }

    private static Path repoRoot() {
        // The test classes live at core/build/classes/java/headlessTest; walk out to the repo.
        Path here = ClassReferences.mainClassesRoot(PortLedgerTest.class);
        for (Path p = here; p != null; p = p.getParent()) {
            if (Files.isRegularFile(p.resolve("settings.gradle.kts"))) return p;
        }
        throw new IllegalStateException("cannot find the repository root from " + here);
    }

    private static List<String> rows(String table) throws IOException {
        Path ledger = repoRoot().resolve(LEDGER);
        assertTrue("the ledger is missing -- run: python tools/port/ledger.py", Files.isRegularFile(ledger));
        List<String> out = new ArrayList<>();
        for (String line : Files.readAllLines(ledger, StandardCharsets.UTF_8)) {
            if (line.startsWith(table + "\t")) out.add(line);
        }
        return out;
    }

    private static List<ClassRow> classes() throws IOException {
        List<ClassRow> out = new ArrayList<>();
        for (String line : rows("CLASS")) {
            String[] f = line.split("\t");
            out.add(new ClassRow(f[1], f[3], f[4], f[5], f[6]));
        }
        return out;
    }

    private static List<PartRow> parts() throws IOException {
        List<PartRow> out = new ArrayList<>();
        for (String line : rows("PART")) {
            String[] f = line.split("\t");
            out.add(new PartRow(f[1], f[2], f[3], f[5]));
        }
        return out;
    }

    /**
     * Every class in port scope is in the ledger, and every ledger row names a real file.
     *
     * <p>The direction that matters is the first: a widget added to {@code ui/elements} without a
     * ledger row is a widget nobody has decided the destination of, and it would be discovered in the
     * middle of the batch that trips over it.</p>
     */
    @Test
    public void theLedgerAndTheTreeAgreeAboutWhatIsBeingPorted() throws IOException {
        Path root = repoRoot();
        Set<String> ledgered = new LinkedHashSet<>();
        List<String> missingFiles = new ArrayList<>();
        for (ClassRow row : classes()) {
            ledgered.add(row.path());
            if ("ported".equals(row.status())) continue;
            // The Run panel is in `language/`, whose package root is com/crystalgui/LANGUAGE -- so the
            // ledger's `language/run/view/X` is that module's `com/crystalgui/language/run/view/X`.
            Path source = row.path().startsWith("language/")
                    ? root.resolve("language/src/main/java/com/crystalgui/language")
                            .resolve(row.path().substring("language/".length()) + ".java")
                    : root.resolve("core/src/main/java/com/crystalgui").resolve(row.path() + ".java");
            if (!Files.isRegularFile(source)) missingFiles.add(row.path());
        }
        assertTrue("the ledger names files that do not exist -- regenerate with "
                + "`python tools/port/ledger.py`:\n" + String.join("\n", missingFiles), missingFiles.isEmpty());

        List<String> unledgered = new ArrayList<>();
        Path elements = root.resolve("core/src/main/java/com/crystalgui/ui/elements");
        try (var walk = Files.walk(elements)) {
            for (Path p : walk.toList()) {
                String name = p.getFileName().toString();
                if (!name.endsWith(".java") || name.equals("package-info.java")) continue;
                String rel = elements.getParent().getParent().relativize(p).toString()
                        .replace('\\', '/').replaceAll("\\.java$", "");
                if (!ledgered.contains(rel)) unledgered.add(rel);
            }
        }
        assertTrue("in port scope but not in the ledger -- a widget nobody has decided the "
                + "destination of:\n" + String.join("\n", unledgered), unledgered.isEmpty());
    }

    /**
     * A PORTED class's parts must be CONFIRMED, never still the generator's proposal.
     *
     * <p>The check bites when the answer is about to be used rather than before it is: the heuristic
     * is right most of the time and wrong in exactly the cases that matter, and the first run proved
     * it — {@code thumb}, {@code mark}, {@code label} and {@code track}, the archetypal parts of
     * Slider, Checkbox, Button and Scroller, all came back as light structure because a sheet scopes
     * them through a container. Being SCOPED BY an ancestor says nothing about whether you hold
     * anything; being SELECTED THROUGH says you do. Every kind therefore gets read by a human before
     * the widget that owns it moves.</p>
     */
    @Test
    public void aPortedClassHasConfirmedParts() throws IOException {
        boolean anythingPorted = classes().stream().anyMatch(r -> "ported".equals(r.status()));
        if (!anythingPorted) return;
        List<String> unconfirmed = new ArrayList<>();
        for (PartRow part : parts()) {
            if (!"confirmed".equals(part.source())) {
                unconfirmed.add(part.owner() + "/" + part.name() + " (" + part.kind() + ")");
            }
        }
        assertTrue("the port has begun and these part kinds are still the generator's guess:\n"
                + String.join("\n", unconfirmed), unconfirmed.isEmpty());
    }

    /** Every row is one of the three kinds, and every class row carries a batch and a destination. */
    @Test
    public void everyRowIsWellFormed() throws IOException {
        List<String> bad = new ArrayList<>();
        for (PartRow part : parts()) {
            if (!List.of("A", "B", "C").contains(part.kind())) {
                bad.add("part " + part.owner() + "/" + part.name() + ": " + part.kind());
            }
        }
        Map<String, Integer> perBatch = new LinkedHashMap<>();
        for (ClassRow row : classes()) {
            if (row.destination().isEmpty()) bad.add("class " + row.path() + ": no destination");
            if (row.batch().equals("?")) bad.add("class " + row.path() + ": no batch");
            if (!List.of("copy", "move").contains(row.how())) bad.add("class " + row.path() + ": how=" + row.how());
            perBatch.merge(row.batch(), 1, Integer::sum);
        }
        assertTrue(String.join("\n", bad), bad.isEmpty());
        assertTrue("every batch 6.1-6.8 has work in it: " + perBatch, perBatch.size() >= 8);
    }
}
