package com.crystalgui.language.js;

import com.crystalgui.language.engine.bridge.JsExecutor;
import com.crystalgui.language.engine.bridge.LiveScopeSnapshot;
import com.crystalgui.language.engine.bridge.MemberNameMapper;

import org.mozilla.javascript.BaseFunction;
import org.mozilla.javascript.Context;
import org.mozilla.javascript.ContextFactory;
import org.mozilla.javascript.EvaluatorException;
import org.mozilla.javascript.Function;
import org.mozilla.javascript.NativeArray;
import org.mozilla.javascript.NativeJavaClass;
import org.mozilla.javascript.NativeObject;
import org.mozilla.javascript.RhinoException;
import org.mozilla.javascript.Script;
import org.mozilla.javascript.ScriptStackElement;
import org.mozilla.javascript.Scriptable;
import org.mozilla.javascript.ScriptableObject;
import org.mozilla.javascript.Undefined;
import org.mozilla.javascript.WrappedException;
import org.mozilla.javascript.Wrapper;

import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.function.Consumer;
import java.util.function.Predicate;
import java.util.function.Supplier;

/**
 * Rhino, running a script — the engine's side of the execution bridge.
 *
 * <h3>Every entry goes through {@link RhinoThread}</h3>
 *
 * <p>Not ceremony: without the engine loader on the thread, Rhino never finds its regular-expression
 * engine and a script's first regex throws. Read that class — the ordering is subtle and the symptom
 * names nothing that would lead you to it.</p>
 *
 * <h3>Interpreted, deliberately</h3>
 *
 * <p>{@code setOptimizationLevel(-1)}. Instruction counting — the kill switch — is unconditional in the
 * interpreter, where compiled mode needs the codegen to have been told to emit counters; the interpreter
 * emits no class files, so band 8's Java 8 ceiling cannot be violated by generated bytecode; and there
 * is nothing to cache, because Rhino resolves Java members at call time in either mode. A hot handler
 * that wants the compiler is a per-script opt-in worth measuring later, not a default worth guessing
 * now.</p>
 *
 * <h3>The stop, in three parts</h3>
 *
 * <p>{@link #stop(Thread)} sets a flag on the run that thread is executing and interrupts the thread. A
 * <b>spinning</b> script meets the flag at the next instruction-count observation and an {@link Error}
 * is thrown from inside the interpreter loop — an {@code Error} because Rhino's interpreter refuses to
 * let a script's own {@code catch} take one, so no {@code try} in the script can swallow the stop. A
 * <b>blocked</b> script — {@code Thread.sleep} through {@code Java.type}, a {@code readLine()} waiting on
 * the console — is reached by the interrupt, exactly as a Java script is. And at the boundary of
 * {@link #run} both arrive as one thing, {@link InterruptedException}, which the host reads as "stopped"
 * rather than "failed". The flag rather than the interrupt status alone, because {@code Thread.sleep}
 * <em>clears</em> the status when it throws: a script that swallowed the resulting exception would
 * otherwise run on with nothing left to say it had been asked to stop.</p>
 *
 * <h3>The application class loader is the host's — plus Rhino</h3>
 *
 * <p>A class the script names through {@code Java.type} must resolve to the <b>host's</b> definition, or
 * a binding the host handed over and a class the script looked up are two different types with one name.
 * This class cannot simply hand Rhino its own loader: it is defined by the band loader, child-first so that
 * it can see Rhino, and that loader would define its <em>own</em> copy of every host class. Nor can it hand
 * over the host's loader alone — Rhino refuses an application loader that cannot resolve Rhino's own
 * classes ({@code "Loader can not resolve Rhino classes"}), and the host by design cannot. So
 * {@link #APPLICATION_LOADER} is the host's loader with exactly one addition: {@code org.mozilla.*} from
 * the band. The host is found from the <em>bridge</em> interface, which is parent-first by construction
 * and therefore defined by whoever the host is — in a test that puts Rhino on the plain classpath, the
 * two loaders are one and the same, which is also right.</p>
 */
public final class RhinoExecutor implements JsExecutor {

    /** How many interpreted instructions between two looks at the stop flag. */
    private static final int OBSERVER_THRESHOLD = 10_000;

    /** The key the run's stop flag is filed under on its {@code Context}. */
    private static final Object RUN_KEY = new Object();

    /**
     * Every run that is executing, by the thread it is on. @see #stop(Thread)
     */
    private static final ConcurrentHashMap<Thread, Run> RUNS = new ConcurrentHashMap<>();

    /** Host classes from the host, Rhino's from the band. @see JsLoaders, which is the one definition. */
    private static final ClassLoader APPLICATION_LOADER = JsLoaders.APPLICATION;

    /** One context factory for every run — its only job is to route the observer to the run's flag. */
    private static final ContextFactory FACTORY = new ContextFactory() {
        @Override
        protected Context makeContext() {
            Context cx = super.makeContext();
            cx.setLanguageVersion(Context.VERSION_ES6);
            cx.setOptimizationLevel(-1);
            cx.setInstructionObserverThreshold(OBSERVER_THRESHOLD);
            // JAVA STRINGS COME BACK AS JAVASCRIPT STRINGS. Without this, `list.get(0)` from a Java list
            // is a NativeJavaObject wrapping a String -- which compares unequal to 'one', prints as itself
            // and has no `.length`. Rhino's own shell sets exactly this.
            cx.getWrapFactory().setJavaPrimitiveWrap(false);
            // AND THE MEMBER NAMES A SCRIPT WRITES. Identity by default, in which case Rhino's own factory
            // is left in place -- an unmapped deployment runs the path it ran before remapping existed.
            // @see RhinoRemapping, and why this is not a patched JavaMembers
            cx.setWrapFactory(RhinoRemapping.factoryFor(memberNames, cx.getWrapFactory()));
            return cx;
        }

        @Override
        protected void observeInstructionCount(Context cx, int instructionCount) {
            Object run = cx.getThreadLocal(RUN_KEY);
            if (run instanceof Run && ((Run) run).stopRequested) throw new Stopped();
        }
    };

    /** Public no-argument, because {@code EngineHost.adapter} instantiates this reflectively. */
    public RhinoExecutor() {
    }

    /**
     * The readable↔runtime member-name mapping, or identity.
     *
     * <p>Static because the {@code ContextFactory} below is: one factory per process makes one context
     * configuration, and a per-instance mapper would be read by a factory that could not see it.</p>
     */
    private static volatile MemberNameMapper memberNames = MemberNameMapper.IDENTITY;

    @Override
    public void useMemberNames(MemberNameMapper mapper) {
        memberNames = mapper == null ? MemberNameMapper.IDENTITY : mapper;
    }

    // ── Compile ─────────────────────────────────────────────────────────────────────────────────

    @Override
    public Compiled compile(String sourceName, String source) {
        String name = sourceName == null || sourceName.isEmpty() ? "script.js" : sourceName;
        String text = source == null ? "" : source;
        return RhinoThread.with(() -> {
            Context cx = FACTORY.enterContext();
            try {
                return new CompiledScript(cx.compileString(text, name, 1, null),
                        Collections.<String>emptyList());
            } catch (EvaluatorException refused) {
                // AN ORDINARY OUTCOME, not an exception the shell has to catch. The analyser has usually
                // already put the same problem on the same offsets in the editor; this is only the gate
                // that stops a broken script starting, and the message is what a caller with no editor
                // -- a test, a dedicated server -- has to go on.
                return new CompiledScript(null, messagesOf(refused));
            } catch (RuntimeException refused) {
                return new CompiledScript(null, messagesOf(refused));
            } finally {
                Context.exit();
            }
        });
    }

    private static List<String> messagesOf(RuntimeException thrown) {
        List<String> messages = new ArrayList<>(1);
        String message = thrown.getMessage();
        messages.add(message == null || message.isEmpty() ? thrown.toString() : message);
        return messages;
    }

    // ── Run ─────────────────────────────────────────────────────────────────────────────────────

    @Override
    public Object run(Compiled script, Map<String, Object> bindings,
                      Consumer<String> out, Consumer<String> err,
                      Supplier<String> readLine, Predicate<String> allowsClass) throws Throwable {
        if (!(script instanceof CompiledScript) || !script.successful()) {
            throw new IllegalStateException("cannot run a script that did not compile: "
                    + (script == null ? "null" : script.messages()));
        }
        // A CONTEXT ALREADY ENTERED on this thread would be reused by enterContext, and its shutter --
        // which may be set exactly once -- would already be somebody else's. Refusing is the honest
        // answer; nothing of ours nests runs.
        if (Context.getCurrentContext() != null) {
            throw new IllegalStateException("a script is already running on this thread");
        }
        Script compiled = ((CompiledScript) script).script();
        Thread thread = Thread.currentThread();
        // WHAT THE HOST HAD ON THIS THREAD, so the script itself can run under it. @see RhinoThread#withLoader
        ClassLoader hostContext = thread.getContextClassLoader();
        Run run = new Run();
        RUNS.put(thread, run);
        try {
            return RhinoThread.withThrowing(() -> {
                Context cx = FACTORY.enterContext();
                try {
                    cx.putThreadLocal(RUN_KEY, run);
                    cx.setApplicationClassLoader(APPLICATION_LOADER);
                    if (allowsClass != null) cx.setClassShutter(allowsClass::test);
                    // FRESH, every time. Nothing the previous run defined is reachable from here, which
                    // is what "replace" means in a language with no classloader to drop.
                    ScriptableObject scope = cx.initStandardObjects(null, false);
                    installGlobals(cx, scope, run, out, err, readLine, allowsClass);
                    bind(cx, scope, bindings, allowsClass);
                    // WHAT WAS THERE BEFORE THE SCRIPT RAN. The standard library, our console globals and
                    // the host's bindings all live on this same scope, so "what did the run define" is a
                    // difference rather than a listing -- without the baseline the live tier would offer
                    // `Object`, `Math` and `parseInt` as things the script had just created.
                    run.scope = scope;
                    run.baseline = idsOf(scope);
                    // THE SCRIPT RUNS UNDER THE HOST'S CONTEXT LOADER, not ours. Everything Rhino needed
                    // the engine loader for has been resolved by now (the standard objects are built, so
                    // the regular-expression engine is cached); what remains is the script calling OUT,
                    // and leaving a child-first loader on the thread for that makes every ServiceLoader
                    // in the application resolve against the engine's classpath.
                    return RhinoThread.withLoader(hostContext, () -> compiled.exec(cx, scope));
                } catch (Stopped stopped) {
                    throw interrupted();
                } catch (WrappedException wrapped) {
                    // THE BLOCKED HALF OF THE SAME STOP: the interrupt reached a Java call the script was
                    // waiting in. Only when we asked -- an InterruptedException from anywhere else is the
                    // script's own failure and is reported as one.
                    if (run.stopRequested && wrapped.getWrappedException() instanceof InterruptedException) {
                        throw interrupted();
                    }
                    throw wrapped;
                } finally {
                    // ON THE SCRIPT'S OWN THREAD, WHILE THE CONTEXT IS STILL ENTERED, and whether the run
                    // finished or threw -- a script that failed halfway still defined what it defined,
                    // and that is exactly the state somebody debugging wants to look at.
                    LAST_SNAPSHOT.set(snapshotOf(run));
                    run.scope = null;
                    Context.exit();
                }
            });
        } finally {
            RUNS.remove(thread, run);
        }
    }

    private static InterruptedException interrupted() {
        // THE STATUS IS RE-ARMED before the run ends, so the host that asked to stop can see it either
        // way -- and cleared by whoever reads it, which is the JDK's own contract for the flag.
        Thread.currentThread().interrupt();
        return new InterruptedException("script stopped");
    }

    /**
     * The host's objects, in scope by name.
     *
     * <p>Wrapped through {@code javaToJS} so a Java {@code String} is a JavaScript string and a Java object
     * is a live proxy the script can call methods on. A binding whose class the sandbox refuses is not put
     * in scope at all: putting it there and letting the shutter refuse each call would be a name that
     * exists and cannot be used, which is worse than one that does not exist.</p>
     */
    private static void bind(Context cx, Scriptable scope, Map<String, Object> bindings,
                             Predicate<String> allowsClass) {
        if (bindings == null || bindings.isEmpty()) return;
        for (Map.Entry<String, Object> binding : bindings.entrySet()) {
            Object value = binding.getValue();
            if (value != null && allowsClass != null && !allowsClass.test(value.getClass().getName())) {
                continue;
            }
            ScriptableObject.putProperty(scope, binding.getKey(), wrap(cx, scope, value));
        }
    }

    /**
     * A Java value as the script sees it.
     *
     * <p>{@code Context.javaToJS} wraps a {@code Class} as an ordinary object — its members are
     * {@code getName()} and friends, and {@code Sink.write(...)} is "Cannot find function write". A class
     * handed to a script means its <em>statics</em>, which is {@code NativeJavaClass} and is what
     * {@code Packages.a.b.C} would have produced; so a class goes through the wrap factory's class path
     * and everything else through the ordinary one.</p>
     */
    private static Object wrap(Context cx, Scriptable scope, Object value) {
        if (value instanceof Class) return cx.getWrapFactory().wrapJavaClass(cx, scope, (Class<?>) value);
        // THE CONTEXT'S OWN FACTORY, ASKED DIRECTLY, rather than through `Context.javaToJS`. Published
        // Rhino routes the static helper through this same factory, so on paper the two are equivalent --
        // but "on paper" is what the ObjectProperty and Token divergences were as well, and this call
        // cannot diverge from whichever factory is installed on whichever band. It costs nothing to be
        // sure about the one hop the whole member-name mapping hangs from.
        return cx.getWrapFactory().wrap(cx, scope, value, null);
    }

    // ── The globals ─────────────────────────────────────────────────────────────────────────────

    /**
     * {@code console}, {@code print}, {@code readLine}/{@code prompt}, {@code Java}.
     *
     * <p>Host functions rather than a prelude, so nothing shifts an offset: every line the engine reports
     * is the file's own line, which is what makes a runtime error land on the right row without a mapping
     * pass. Rhino's bare {@code initStandardObjects} installs none of these — {@code console} is the
     * shell's, and {@code Java} is Nashorn's, adopted here because {@code Java.type('a.b.C')} is one
     * expression the completion list can insert while {@code Packages.a.b.C} is a chain of four.</p>
     */
    private static void installGlobals(Context cx, ScriptableObject scope, Run run,
                                       Consumer<String> out, Consumer<String> err,
                                       Supplier<String> readLine, Predicate<String> allowsClass) {
        Consumer<String> toOut = out == null ? text -> { } : out;
        Consumer<String> toErr = err == null ? text -> { } : err;

        NativeObject console = new NativeObject();
        console.setPrototype(ScriptableObject.getObjectPrototype(scope));
        console.setParentScope(scope);
        for (String name : new String[]{"log", "info", "debug"}) {
            define(console, scope, name, args -> emit(toOut, args));
        }
        // WARN AND ERROR BOTH GO TO THE ERROR CONSUMER. That is Node's own routing -- both write to
        // stderr -- and the console shows them at the level the host chose for that stream.
        define(console, scope, "warn", args -> emit(toErr, args));
        define(console, scope, "error", args -> emit(toErr, args));
        ScriptableObject.putProperty(scope, "console", console);

        define(scope, scope, "print", args -> emit(toOut, args));

        HostBody read = args -> {
            // A PROMPT IS PRINTED, THEN THE READ BLOCKS. `readLine('Name? ')` is the shape every
            // shell offers, and it lands as a row of its own because the console deals in rows.
            if (args.length > 0 && args[0] != null && !Undefined.isUndefined(args[0])) {
                toOut.accept(RhinoConsoleFormat.topLevel(args[0]));
            }
            String line = readLine == null ? null : readLine.get();
            // A STOP THAT LANDED WHILE WAITING ends the script here, not ten thousand instructions
            // later. The console answered null and restored the interrupt; without this the script
            // would go on with a null in hand until the observer next looked.
            if (run.stopRequested) throw new Stopped();
            return line;
        };
        define(scope, scope, "readLine", read);
        define(scope, scope, "prompt", read);

        NativeObject java = new NativeObject();
        java.setPrototype(ScriptableObject.getObjectPrototype(scope));
        java.setParentScope(scope);
        define(java, scope, "type", args -> {
            String name = args.length == 0 || args[0] == null ? "" : Context.toString(args[0]);
            if (name.isEmpty()) throw new IllegalArgumentException("Java.type: a class name is required");
            // ASKED HERE AS WELL AS AT THE SHUTTER, so a refused class is never even loaded and the
            // message names the class rather than the member the script went on to call.
            if (allowsClass != null && !allowsClass.test(name)) {
                throw new SecurityException("Java.type: access to " + name + " is not permitted");
            }
            // THROUGH THE SHARED LOOKUP, which also tries the nested spelling: a script writes
            // `java.util.Map.Entry` -- the form the editor resolves and offers -- and the JVM knows only
            // `java.util.Map$Entry`, so the name the popup suggested threw at run time.
            Class<?> found = JsLoaders.load(name);
            if (found == null) throw new IllegalArgumentException("Java.type: no such class " + name);
            return wrap(cx, scope, found);
        });
        ScriptableObject.putProperty(scope, "Java", java);
    }

    private static Object emit(Consumer<String> sink, Object[] args) {
        sink.accept(RhinoConsoleFormat.line(args));
        return Undefined.instance;
    }

    /** What a host function does, given the script's arguments. */
    private interface HostBody {
        Object call(Object[] args);
    }

    /** Defines {@code name} on {@code owner} as a function the script can call. */
    private static void define(Scriptable owner, Scriptable scope, String name, HostBody body) {
        BaseFunction function = new BaseFunction(scope, ScriptableObject.getFunctionPrototype(scope)) {
            @Override
            public Object call(Context cx, Scriptable callScope, Scriptable thisObj, Object[] args) {
                return body.call(args == null ? new Object[0] : args);
            }

            @Override
            public String getFunctionName() {
                return name;
            }
        };
        ScriptableObject.putProperty(owner, name, function);
    }

    // ── Stop, origin, failure ───────────────────────────────────────────────────────────────────

    @Override
    public void stop(Thread thread) {
        if (thread == null) return;
        Run run = RUNS.get(thread);
        // ONLY A THREAD WE HAVE A RUN ON. Interrupting one we do not is not the harmless no-op the old
        // comment claimed: it sets the interrupt status of somebody else's thread, and the windows where
        // that happens are real -- a synchronous run whose executor entry has already been removed, or a
        // Stop that lands between a host publishing its run and recording the thread it is on.
        if (run == null) return;
        // THE FLAG FIRST, THEN THE INTERRUPT. A blocked script wakes on the interrupt and asks the flag;
        // the other order has a window where it wakes, sees no request, and goes back to waiting.
        run.stopRequested = true;
        if (thread.isAlive()) thread.interrupt();
    }

    /**
     * The last run on <b>this thread</b>, snapshotted.
     *
     * <p>Per thread because that is what identifies a run once it is over: {@code RUNS} is keyed the same
     * way and is emptied when the run returns, and the host asks for this immediately afterwards on the
     * same thread. A daemon script thread dies with its run, so nothing accumulates.</p>
     */
    private static final ThreadLocal<LiveScopeSnapshot> LAST_SNAPSHOT = new ThreadLocal<>();

    @Override
    public LiveScopeSnapshot snapshotScope() {
        LiveScopeSnapshot taken = LAST_SNAPSHOT.get();
        return taken == null ? LiveScopeSnapshot.EMPTY : taken;
    }

    /**
     * Walks the run's global scope once, into types that hold nothing of Rhino's.
     *
     * <p>Every property read is guarded, because a property can be a getter and a getter is somebody's
     * code: a script that defines one which throws must not take the snapshot -- and with it the whole
     * run's reporting -- down with it. The name is still recorded, as something whose kind is unknown.</p>
     */
    private static LiveScopeSnapshot snapshotOf(Run run) {
        ScriptableObject scope = run.scope;
        if (scope == null) return LiveScopeSnapshot.EMPTY;
        List<LiveScopeSnapshot.Entry> entries = new ArrayList<>();
        for (Object id : scope.getIds()) {
            if (!(id instanceof String)) continue;
            String name = (String) id;
            if (run.baseline != null && run.baseline.contains(name)) continue;
            try {
                entries.add(describe(name, ScriptableObject.getProperty(scope, name)));
            } catch (RuntimeException | StackOverflowError unreadable) {
                entries.add(LiveScopeSnapshot.Entry.of(name, LiveScopeSnapshot.Kind.OTHER));
            }
        }
        // AND WHAT EVERY OBJECT INHERITS, read from this run's own Object.prototype rather than written
        // down: it is the engine's list, it differs by band as the standard library grows, and a
        // completion row marked "inherited" has to be one that actually is.
        return LiveScopeSnapshot.of(entries, allIdsOf(ScriptableObject.getObjectPrototype(scope)));
    }

    private static Set<String> idsOf(ScriptableObject scope) {
        Set<String> ids = new LinkedHashSet<>();
        for (Object id : scope.getIds()) {
            if (id instanceof String) ids.add((String) id);
        }
        return ids;
    }

    /** One live value, classified. */
    private static LiveScopeSnapshot.Entry describe(String name, Object value) {
        if (value == null || value == Scriptable.NOT_FOUND) {
            return LiveScopeSnapshot.Entry.of(name, LiveScopeSnapshot.Kind.NULL);
        }
        if (Undefined.isUndefined(value)) {
            return LiveScopeSnapshot.Entry.of(name, LiveScopeSnapshot.Kind.UNDEFINED);
        }
        // A JAVA VALUE, CLASS OR INSTANCE — TOLD APART BY WHAT IT WRAPS, never by the wrapper's own class.
        // Under a member-name mapping every Java value arrives inside a membrane (@see RhinoRemapping), so
        // it is not a NativeJavaClass however plainly it is a class: `var W = Java.type('…')` was reported
        // as an INSTANCE of java.lang.Class, and `W.` then listed Class's own members.
        if (value instanceof Wrapper) {
            Object unwrapped = ((Wrapper) value).unwrap();
            if (unwrapped instanceof Class) {
                return new LiveScopeSnapshot.Entry(name, LiveScopeSnapshot.Kind.JAVA_CLASS,
                        ((Class<?>) unwrapped).getName(), null, -1, List.of());
            }
            return new LiveScopeSnapshot.Entry(name, LiveScopeSnapshot.Kind.JAVA_OBJECT,
                    unwrapped == null ? null : unwrapped.getClass().getName(), null, -1, List.of());
        }
        if (value instanceof BaseFunction) {
            BaseFunction function = (BaseFunction) value;
            return new LiveScopeSnapshot.Entry(name, LiveScopeSnapshot.Kind.FUNCTION, null,
                    function.getFunctionName(), function.getArity(), ownIdsOf(function));
        }
        if (value instanceof Function) {
            return new LiveScopeSnapshot.Entry(name, LiveScopeSnapshot.Kind.FUNCTION, null, name, -1,
                    List.<String>of());
        }
        if (value instanceof NativeArray) {
            return LiveScopeSnapshot.Entry.of(name, LiveScopeSnapshot.Kind.ARRAY);
        }
        if (value instanceof CharSequence) {
            return LiveScopeSnapshot.Entry.of(name, LiveScopeSnapshot.Kind.STRING);
        }
        if (value instanceof Number) return LiveScopeSnapshot.Entry.of(name, LiveScopeSnapshot.Kind.NUMBER);
        if (value instanceof Boolean) {
            return LiveScopeSnapshot.Entry.of(name, LiveScopeSnapshot.Kind.BOOLEAN);
        }
        if (value instanceof Scriptable) {
            Scriptable object = (Scriptable) value;
            String className = object.getClassName();
            if ("Object".equals(className)) {
                return new LiveScopeSnapshot.Entry(name, LiveScopeSnapshot.Kind.OBJECT, null, null, -1,
                        ownIdsOf(object));
            }
            if ("RegExp".equals(className)) {
                return LiveScopeSnapshot.Entry.of(name, LiveScopeSnapshot.Kind.REGEXP);
            }
            return LiveScopeSnapshot.Entry.of(name, LiveScopeSnapshot.Kind.OTHER);
        }
        return LiveScopeSnapshot.Entry.of(name, LiveScopeSnapshot.Kind.OTHER);
    }

    /**
     * Every id including the non-enumerable ones — which is what a PROTOTYPE's are.
     *
     * <p>{@code getIds()} answers only enumerable properties, and {@code toString}, {@code valueOf} and
     * {@code hasOwnProperty} are all non-enumerable by specification. So the obvious accessor reports
     * {@code Object.prototype} as having <em>no members at all</em>, and the completion list quietly loses
     * everything every object inherits.</p>
     */
    private static List<String> allIdsOf(Scriptable object) {
        if (!(object instanceof ScriptableObject)) return ownIdsOf(object);
        try {
            List<String> ids = new ArrayList<>();
            for (Object id : ((ScriptableObject) object).getAllIds()) {
                if (id instanceof String) ids.add((String) id);
            }
            return ids;
        } catch (RuntimeException unreadable) {
            return List.of();
        }
    }

    /** An object's OWN property names -- never its prototype's, which are the standard library's. */
    private static List<String> ownIdsOf(Scriptable object) {
        List<String> ids = new ArrayList<>();
        try {
            for (Object id : object.getIds()) {
                if (id instanceof String) ids.add((String) id);
            }
        } catch (RuntimeException unreadable) {
            return List.of();
        }
        return ids;
    }

    @Override
    public int currentLine() {
        Context cx = Context.getCurrentContext();
        if (cx == null) return -1;
        try {
            // AN EXCEPTION IS THE PUBLIC ROUTE. Constructing one captures the interpreter's frame chain
            // (a linked list, not a Java stack walk), and its first element is the innermost script frame
            // -- the line the current statement began on, which is what "the line that printed" means.
            ScriptStackElement[] stack = new EvaluatorException("origin").getScriptStack();
            return stack.length == 0 ? -1 : stack[0].lineNumber;
        } catch (RuntimeException unavailable) {
            return -1;
        }
    }

    @Override
    public Failure describe(Throwable thrown) {
        if (!(thrown instanceof RhinoException)) return null;
        RhinoException error = (RhinoException) thrown;
        String message = error.details();
        if (message == null || message.isEmpty()) message = thrown.toString();
        return new Failure(error.sourceName(), error.lineNumber(), error.columnNumber(), message);
    }

    // ── Types ───────────────────────────────────────────────────────────────────────────────────

    /** One run's stop flag. Filed on the {@code Context}, found by thread. */
    private static final class Run {
        volatile boolean stopRequested;
        /** The run's scope, held only until the snapshot is taken in the same {@code finally}. */
        volatile ScriptableObject scope;
        /** What was on the scope before the script ran. @see #snapshotOf */
        volatile Set<String> baseline;
    }

    /**
     * Thrown from inside the interpreter loop to end a script.
     *
     * <p>An {@code Error} because Rhino refuses a script's {@code catch} an {@code Error} thrown from Java
     * — the same property {@code ScriptStoppedException} has on the Java side, for the same reason. No
     * stack trace: it names an arbitrary loop iteration and costs more than every observation that led to
     * it. Never leaves {@link #run}, which translates it.</p>
     */
    private static final class Stopped extends Error {
        private static final long serialVersionUID = 1L;

        Stopped() {
            super("script stopped", null, false, false);
        }
    }

    /** A compiled script, or the reasons there is not one. */
    private static final class CompiledScript implements Compiled {

        private final Script script;
        private final List<String> messages;

        CompiledScript(Script script, List<String> messages) {
            this.script = script;
            this.messages = messages;
        }

        @Override
        public boolean successful() {
            return script != null;
        }

        @Override
        public List<String> messages() {
            return messages;
        }

        /** The Rhino handle. Never leaves this package. */
        Script script() {
            return script;
        }
    }
}
