package com.crystalgui.language.js;

import com.crystalgui.language.engine.bridge.JsExecutor;

import org.mozilla.javascript.Context;
import org.mozilla.javascript.EvaluatorException;
import org.mozilla.javascript.Script;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;
import java.util.function.Predicate;
import java.util.function.Supplier;

/**
 * Rhino, running a script — the engine's side of the execution bridge.
 *
 * <h3>Every entry goes through {@link RhinoThread}</h3>
 *
 * <p>Not ceremony: without the engine loader on the thread, Rhino never finds its regular-expression
 * engine and a script's first regex throws. Read that class — the ordering is subtle and the symptom
 * names nothing that would lead you to it.</p>
 *
 * <h3>Interpreted, deliberately</h3>
 *
 * <p>{@code setOptimizationLevel(-1)}. Instruction counting — the kill switch — is unconditional in the
 * interpreter, where compiled mode needs the codegen to have been told to emit counters; the interpreter
 * emits no class files, so band 8's Java 8 ceiling cannot be violated by generated bytecode; and there
 * is nothing to cache, because Rhino resolves Java members at call time in either mode. A hot handler
 * that wants the compiler is a per-script opt-in worth measuring later, not a default worth guessing
 * now.</p>
 *
 * <h3>What is here at M10.2</h3>
 *
 * <p>Compiling, which is what the Run command needs to refuse a broken script, and what proves the
 * bridge carries traffic. {@link #run}, {@link #stop} and {@link #currentLine} arrive at M10.5 with the
 * scope, the console globals and the instruction observer; until then running throws rather than
 * pretending, because a Run that silently did nothing is worse than one that says it is not built.</p>
 */
public final class RhinoExecutor implements JsExecutor {

    /** Public no-argument, because {@code EngineHost.adapter} instantiates this reflectively. */
    public RhinoExecutor() {
    }

    @Override
    public Compiled compile(String sourceName, String source) {
        String name = sourceName == null || sourceName.isEmpty() ? "script.js" : sourceName;
        String text = source == null ? "" : source;
        return RhinoThread.with(() -> {
            Context cx = Context.enter();
            try {
                cx.setLanguageVersion(Context.VERSION_ES6);
                cx.setOptimizationLevel(-1);
                cx.setApplicationClassLoader(RhinoExecutor.class.getClassLoader());
                return new CompiledScript(cx.compileString(text, name, 1, null),
                        Collections.<String>emptyList());
            } catch (EvaluatorException refused) {
                // AN ORDINARY OUTCOME, not an exception the shell has to catch. The analyser has usually
                // already put the same problem on the same offsets in the editor; this is only the gate
                // that stops a broken script starting, and the message is what a caller with no editor
                // -- a test, a dedicated server -- has to go on.
                return new CompiledScript(null, messagesOf(refused));
            } catch (RuntimeException refused) {
                return new CompiledScript(null, messagesOf(refused));
            } finally {
                Context.exit();
            }
        });
    }

    private static List<String> messagesOf(RuntimeException thrown) {
        List<String> messages = new ArrayList<>(1);
        String message = thrown.getMessage();
        messages.add(message == null || message.isEmpty() ? thrown.toString() : message);
        return messages;
    }

    @Override
    public Object run(Compiled script, Map<String, Object> bindings,
                      Consumer<String> out, Consumer<String> err,
                      Supplier<String> readLine, Predicate<String> allowsClass) {
        throw new UnsupportedOperationException(
                "the JavaScript runtime lands at M10.5; this build compiles but does not run scripts");
    }

    @Override
    public void stop() {
        // Nothing runs yet, so there is nothing to stop -- and answering rather than throwing is right:
        // `ScriptRuntimes.stopAll()` asks every runtime unconditionally, and one that threw would take
        // down a Stop that was about somebody else's script.
    }

    @Override
    public int currentLine() {
        return -1;
    }

    /** A compiled script, or the reasons there is not one. */
    private static final class CompiledScript implements Compiled {

        private final Script script;
        private final List<String> messages;

        CompiledScript(Script script, List<String> messages) {
            this.script = script;
            this.messages = messages;
        }

        @Override
        public boolean successful() {
            return script != null;
        }

        @Override
        public List<String> messages() {
            return messages;
        }

        /** The Rhino handle, for {@link RhinoExecutor#run} when it lands. Never leaves this package. */
        Script script() {
            return script;
        }
    }
}
