package com.crystalgui.language.map;

import com.crystalgui.language.engine.EngineBand;
import com.crystalgui.language.engine.EngineSource;
import com.crystalgui.language.engine.JavaEngine;
import com.crystalgui.language.engine.ScriptClassLoader;
import com.crystalgui.language.engine.bridge.ScriptCompiler;
import com.crystalgui.language.engine.bridge.SourceAnalyzer;
import com.crystalgui.text.diagnostic.Diagnostic;
import com.crystalgui.text.diagnostic.DiagnosticSeverity;

import org.junit.Assume;
import org.junit.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Map;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;
import com.crystalgui.language.engine.bridge.Analysis;

/**
 * <b>The remap round-trip — M6's last exit criterion.</b>
 *
 * <p>A script authored in <em>readable</em> names compiles, links and runs against a fixture whose
 * runtime members carry synthetic obfuscated names, through a fake mapping set. Both directions of the
 * boundary are exercised on real bytecode: the compiler is shown a view generated by remapping the
 * runtime class runtime→readable, and the compiled script is remapped readable→runtime before it is
 * defined.</p>
 *
 * <p>The fixture is deliberately shaped to include the case that fails silently — a script class
 * <b>overriding</b> a mapped method — because a naive remapper passes every other test here.</p>
 */
public class RemapRoundTripTest {

    // ── The fixture, standing in for a Minecraft class ──────────────────────────────────────────

    /**
     * What the RUNTIME has. Members are named as production would name them; nothing that runs ever
     * sees the readable spelling.
     */
    public static class RuntimeWorld {
        public String m_1234() {
            return "runtime-value";
        }

        public String m_9999() {
            return "base-" + m_1234();
        }

        public int f_5678 = 42;
    }

    /** {@code m_1234} ⇄ {@code getBlock}, {@code m_9999} ⇄ {@code describe}, {@code f_5678} ⇄ {@code depth}. */
    private static MappingSet mappings() {
        String world = RuntimeWorld.class.getName().replace('.', '/');
        return MappingSet.builder()
                .method(world, "m_1234", "getBlock")
                .method(world, "m_9999", "describe")
                .field(world, "f_5678", "depth")
                .build();
    }

    private static JavaEngine openEngine() throws Exception {
        EngineBand band = EngineBand.detect();
        String paths = System.getProperty("cgui.test.engineBand" + band.minimumFeatureVersion());
        EngineSource source = EngineSource.ofPathList(paths);
        Assume.assumeTrue("no jars supplied for band " + band + "; skipping",
                !source.jarsFor(band).isEmpty());
        return JavaEngine.open(band, source);
    }

    /** The readable view of the fixture, as a classpath entry. */
    private static Path readableViewOf(MappingSet mappings) throws IOException {
        return new ReadableView(mappings,
                ReadableView.ByteSource.ofClassLoader(RemapRoundTripTest.class.getClassLoader()))
                .materialiseTemporary(List.of(RuntimeWorld.class.getName().replace('.', '/')));
    }

    private static void deleteTree(Path root) {
        if (root == null) return;
        try (var walk = Files.walk(root)) {
            walk.sorted(Comparator.reverseOrder()).forEach(path -> {
                try {
                    Files.deleteIfExists(path);
                } catch (IOException ignored) {
                    // A temp directory outliving one test is not worth failing it over.
                }
            });
        } catch (IOException ignored) {
            // Same.
        }
    }

    private static List<String> classpathWith(Path readableView) {
        List<String> entries = new ArrayList<>();
        // THE READABLE VIEW FIRST. It shadows the real class, which is the point: the compiler must
        // resolve `getBlock` and must NOT also see `m_1234`, or a script could name either and only
        // one of them would survive the remap.
        entries.add(readableView.toString());
        for (String entry : System.getProperty("java.class.path")
                .split(java.util.regex.Pattern.quote(java.io.File.pathSeparator))) {
            if (!entry.trim().isEmpty()) entries.add(entry.trim());
        }
        return entries;
    }

    // ── The "in" direction on its own ───────────────────────────────────────────────────────────

    @Test
    public void theCompilerSeesReadableNamesForARuntimeObfuscatedClass() throws Exception {
        MappingSet mappings = mappings();
        Path view = readableViewOf(mappings);
        JavaEngine engine = openEngine();
        try {
            String script = ""
                    + "public class Script {\n"
                    + "    " + RuntimeWorld.class.getCanonicalName() + " world;\n"
                    + "    String run() { return world.getBlock() + world.depth; }\n"
                    + "}\n";
            SourceAnalyzer.Analysis analysis = engine.analyzer().analyze(
                    "Script", script, classpathWith(view), engine.releaseLevel(), 1L);
            try {
                for (Diagnostic problem : analysis.diagnostics()) {
                    assertFalse("the readable view did not resolve: " + problem,
                            problem.severity() == DiagnosticSeverity.ERROR);
                }
            } finally {
                analysis.close();
            }
        } finally {
            engine.close();
            deleteTree(view);
        }
    }

    @Test
    public void theCompilerDoesNotSeeTheRuntimeNames() throws Exception {
        // The other half of "one authoring namespace". A script naming `m_1234` must NOT compile, or
        // authors would write runtime names by accident and those break on the next environment.
        MappingSet mappings = mappings();
        Path view = readableViewOf(mappings);
        JavaEngine engine = openEngine();
        try {
            String script = ""
                    + "public class Script {\n"
                    + "    " + RuntimeWorld.class.getCanonicalName() + " world;\n"
                    + "    String run() { return world.m_1234(); }\n"
                    + "}\n";
            SourceAnalyzer.Analysis analysis = engine.analyzer().analyze(
                    "Script", script, classpathWith(view), engine.releaseLevel(), 1L);
            try {
                boolean refused = false;
                for (Diagnostic problem : analysis.diagnostics()) {
                    if (problem.severity() == DiagnosticSeverity.ERROR) refused = true;
                }
                assertTrue("the runtime name resolved — the view is not shadowing the real class",
                        refused);
            } finally {
                analysis.close();
            }
        } finally {
            engine.close();
            deleteTree(view);
        }
    }

    // ── The whole round trip ────────────────────────────────────────────────────────────────────

    @Test
    public void aScriptWrittenInReadableNamesCompilesLinksAndRuns() throws Exception {
        MappingSet mappings = mappings();
        Path view = readableViewOf(mappings);
        JavaEngine engine = openEngine();
        try {
            String script = ""
                    + "public class Script {\n"
                    + "    public static String run(" + RuntimeWorld.class.getCanonicalName() + " world) {\n"
                    + "        return world.getBlock() + \"/\" + world.depth;\n"
                    + "    }\n"
                    + "}\n";

            ScriptCompiler.Result compiled = engine.compiler().compile(
                    "Script", script, classpathWith(view), engine.releaseLevel());
            assertTrue("compile failed: " + compiled.messages(), compiled.successful());

            Map<String, byte[]> runtimeReady = new InheritanceAwareRemapper(mappings,
                    InheritanceAwareRemapper.fromClassLoader(getClass().getClassLoader()))
                    .remap(compiled.classes());

            ScriptClassLoader loader =
                    new ScriptClassLoader(runtimeReady, getClass().getClassLoader());
            Class<?> loaded = Class.forName("Script", true, loader);
            Object answer = loaded.getMethod("run", RuntimeWorld.class)
                    .invoke(null, new RuntimeWorld());

            // Linked against m_1234 and f_5678, which is the only reason this returns anything at all.
            assertEquals("runtime-value/42", answer);
        } finally {
            engine.close();
            deleteTree(view);
        }
    }

    @Test
    public void anOverrideSTAYSAnOverride() throws Exception {
        // THE ONE A NAIVE REMAPPER GETS WRONG, and it gets it wrong silently: the call sites are
        // renamed, the DECLARATION is not, the class verifies and loads, and the script's method is
        // simply never called. No exception, nothing to search for. This is why the remapper walks
        // supertypes rather than trusting the declaring owner.
        MappingSet mappings = mappings();
        Path view = readableViewOf(mappings);
        JavaEngine engine = openEngine();
        try {
            String script = ""
                    + "public class Script extends " + RuntimeWorld.class.getCanonicalName() + " {\n"
                    + "    @Override public String getBlock() { return \"overridden\"; }\n"
                    // CALLED THROUGH A RuntimeWorld-TYPED REFERENCE, so the call site owner is the
                    // mapped type and both remappers rename `describe` identically. That leaves the
                    // OVERRIDE as the only difference between the two runs, which is the point of
                    // the pair. Through `new Script().describe()` the owner is Script, a naive
                    // remapper leaves it alone, and it fails loudly with NoSuchMethodError before
                    // ever reaching the silent case.
                    + "    public static String run() {\n"
                    + "        " + RuntimeWorld.class.getCanonicalName() + " w = new Script();\n"
                    + "        return w.describe();\n"
                    + "    }\n"
                    + "}\n";

            ScriptCompiler.Result compiled = engine.compiler().compile(
                    "Script", script, classpathWith(view), engine.releaseLevel());
            assertTrue("compile failed: " + compiled.messages(), compiled.successful());

            Map<String, byte[]> runtimeReady = new InheritanceAwareRemapper(mappings,
                    InheritanceAwareRemapper.fromClassLoader(getClass().getClassLoader()))
                    .remap(compiled.classes());

            ScriptClassLoader loader =
                    new ScriptClassLoader(runtimeReady, getClass().getClassLoader());
            Object answer = Class.forName("Script", true, loader).getMethod("run").invoke(null);

            // `describe` is RuntimeWorld.m_9999, which calls m_1234. If the override was renamed
            // correctly it reaches the script's method; if not, it reaches the base and returns
            // "base-runtime-value" -- which is exactly the silent failure.
            assertEquals("the override was not renamed — the script's method never ran",
                    "base-overridden", answer);
        } finally {
            engine.close();
            deleteTree(view);
        }
    }

    @Test
    public void withoutPropagationTheOverrideSILENTLYStopsBeingOne() throws Exception {
        // THE NEGATIVE CONTROL, against a REAL plain ClassRemapper -- which is what §15.5 means by
        // "not a naive ClassRemapper". It asks about the declaring owner and nothing else, so a
        // declaration in the script is never renamed.
        //
        // Written first as "our remapper with the hierarchy blinded", which did NOT fail: passing
        // Hierarchy.NONE blinds only the HOST's hierarchy, because `withLocalClasses` always reads the
        // supertypes of the classes being remapped out of their own bytes. That is correct and load-
        // bearing -- it is what makes a script's nested class extending an MC type work without the
        // caller knowing it exists -- and it meant the control proved nothing. Recorded because a
        // negative control that cannot fail is the same trap as an assertion that cannot.
        //
        // Note what does NOT happen below: no exception, no verify error, no diagnostic. The class
        // loads and runs and returns the wrong string. That is the whole argument for the walk.
        MappingSet mappings = mappings();
        Path view = readableViewOf(mappings);
        JavaEngine engine = openEngine();
        try {
            String script = ""
                    + "public class Script extends " + RuntimeWorld.class.getCanonicalName() + " {\n"
                    + "    @Override public String getBlock() { return \"overridden\"; }\n"
                    // CALLED THROUGH A RuntimeWorld-TYPED REFERENCE, so the call site owner is the
                    // mapped type and both remappers rename `describe` identically. That leaves the
                    // OVERRIDE as the only difference between the two runs, which is the point of
                    // the pair. Through `new Script().describe()` the owner is Script, a naive
                    // remapper leaves it alone, and it fails loudly with NoSuchMethodError before
                    // ever reaching the silent case.
                    + "    public static String run() {\n"
                    + "        " + RuntimeWorld.class.getCanonicalName() + " w = new Script();\n"
                    + "        return w.describe();\n"
                    + "    }\n"
                    + "}\n";
            ScriptCompiler.Result compiled = engine.compiler().compile(
                    "Script", script, classpathWith(view), engine.releaseLevel());
            assertTrue("compile failed: " + compiled.messages(), compiled.successful());

            Map<String, byte[]> naive = new java.util.HashMap<>();
            for (Map.Entry<String, byte[]> entry : compiled.classes().entrySet()) {
                org.objectweb.asm.ClassReader reader =
                        new org.objectweb.asm.ClassReader(entry.getValue());
                org.objectweb.asm.ClassWriter writer =
                        new org.objectweb.asm.ClassWriter(reader, 0);
                reader.accept(new org.objectweb.asm.commons.ClassRemapper(writer,
                        new org.objectweb.asm.commons.Remapper() {
                            @Override
                            public String mapMethodName(String owner, String name, String descriptor) {
                                return mappings.runtimeMethod(owner, name);
                            }

                            @Override
                            public String mapFieldName(String owner, String name, String descriptor) {
                                return mappings.runtimeField(owner, name);
                            }
                        }), 0);
                naive.put(entry.getKey(), writer.toByteArray());
            }

            ScriptClassLoader loader = new ScriptClassLoader(naive, getClass().getClassLoader());
            Object answer = Class.forName("Script", true, loader).getMethod("run").invoke(null);

            assertEquals("the naive remap produced the RIGHT answer — so the test above proves nothing",
                    "base-runtime-value", answer);
        } finally {
            engine.close();
            deleteTree(view);
        }
    }

    // ── The identity case, which is most hosts ──────────────────────────────────────────────────

    @Test
    public void anIdentityMappingReturnsTheInputUntouched() {
        Map<String, byte[]> classes = Map.of("Script", new byte[]{1, 2, 3});
        Map<String, byte[]> out = new InheritanceAwareRemapper(
                MappingSet.IDENTITY, InheritanceAwareRemapper.Hierarchy.NONE).remap(classes);
        assertTrue("a dev environment must pay nothing for the boundary", classes == out);
    }

    // ── The mapping model itself ────────────────────────────────────────────────────────────────

    @Test
    public void memberNamesAreKeyedByOwner() {
        // Two classes with a same-named member mapped differently. Keying on the bare name works on a
        // fixture and corrupts a real mapping set SILENTLY -- the wrong member is renamed and the
        // result still verifies.
        MappingSet mappings = MappingSet.builder()
                .method("a/One", "m_1", "value")
                .method("a/Two", "m_2", "value")
                .build();

        assertEquals("m_1", mappings.runtimeMethod("a/One", "value"));
        assertEquals("m_2", mappings.runtimeMethod("a/Two", "value"));
        assertEquals("an unmapped owner must pass the name through",
                "value", mappings.runtimeMethod("a/Three", "value"));
    }

    @Test
    public void aClassRenameCarriesItsMembersToTheReadableOwner() {
        MappingSet mappings = MappingSet.builder()
                .type("a/C_1", "net/example/World")
                .method("a/C_1", "m_1", "getBlock")
                .build();

        assertEquals("net/example/World", mappings.readableClass("a/C_1"));
        assertEquals("a/C_1", mappings.runtimeClass("net/example/World"));
        // Reversed under the READABLE owner, because that is the only name the out direction ever has.
        assertEquals("m_1", mappings.runtimeMethod("net/example/World", "getBlock"));
    }

    @Test
    public void aCycleInTheHierarchyDoesNotHang() {
        // A malformed or adversarial class file can describe one, and an unguarded walk hangs the
        // compile rather than failing it.
        InheritanceAwareRemapper.Hierarchy cyclic = internalName ->
                "A".equals(internalName) ? List.of("B") : List.of("A");
        MappingSet mappings = MappingSet.builder().method("Z", "m_1", "value").build();
        try {
            new InheritanceAwareRemapper(mappings, cyclic).remap(Map.of());
        } catch (StackOverflowError overflowed) {
            fail("the supertype walk recursed without a guard");
        }
        assertNotNull(mappings);
    }
}
